[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"

[build.environment]
NODE_ENV = "production"

[deploy.environment]
NODE_ENV = "production"